name: medhub_adsdigital_msibselection
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  after_layout: ^1.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^10.0.1
  flutter_bloc: ^8.1.6
  carousel_slider: ^5.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/illustrations/
    - assets/brands/
    - assets/payments/

  fonts:
    - family: Overpass
      fonts:
        - asset: fonts/Overpass/Overpass-Black.ttf
          weight: 900
        - asset: fonts/Overpass/Overpass-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Overpass/Overpass-ExtraBold.ttf
          weight: 800
        - asset: fonts/Overpass/Overpass-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Overpass/Overpass-Bold.ttf
          weight: 700
        - asset: fonts/Overpass/Overpass-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Overpass/Overpass-SemiBold.ttf
          weight: 600
        - asset: fonts/Overpass/Overpass-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Overpass/Overpass-Medium.ttf
          weight: 500
        - asset: fonts/Overpass/Overpass-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Overpass/Overpass-Regular.ttf
          weight: 400
        - asset: fonts/Overpass/Overpass-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Overpass/Overpass-Light.ttf
          weight: 300
        - asset: fonts/Overpass/Overpass-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Overpass/Overpass-ExtraLight.ttf
          weight: 200
        - asset: fonts/Overpass/Overpass-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Overpass/Overpass-Thin.ttf
          weight: 100
        - asset: fonts/Overpass/Overpass-ThinItalic.ttf
          style: italic
          weight: 100
